### ISSUE TITLE
[Long running shim session] Release session and temporary arrays gracefully

### ISSUE THREAD

**Issue by ksens** [Paradigm4/shim#68]
@rvernica 

Some more thoughts on automatic cleanup. 

1.
You mentioned we should call `scidbdisconnect(db)` on `finalize`. This would make sure that the session is automatically released if `db` object goes out of scope, and user forgets to explicitly call the `scidbdisconnect` function. Can you suggest a method to do this in R?

2. 
In scidbR, the `as.scidb()` class of upload functions create temporary arrays in SciDB (e.g. `R_array...`). In current `master` implementation of scidbR, the R variable that holds links to the temporary arrays stores a copy of the scidb username-password. So when the R variable goes out of scope, a new session is created, the temporary array is deleted, and scidb/shim session is closed. 

We need to do something similar in the long-running shim session case. Desired behavior would be something like this:

```
# When user has done
x = as.scidb(db, iris)
```

R variable `x` stores the shim session ID in `x@meta$db$session`. When R variable linking to temporary array goes out of scope, the same session is used to delete the temporary array.

One must make sure that the session release happens after the temporary arrays are deleted. 

### Corner case

Even after implementing the above, I see a potential leak. 

i. `x` stores link to temporary scidb array
ii. `scidbdisconnect()` is called explicitly
iii. `x` goes out of scope. It tries to delete temporary array using the session id stored in it. But that session has been released already. So it cannot delete

**Comment by rvernica** [comment]
This looks like a SciDB-R issue and not a Shim issue.

1. I was thinking of something like [this](https://stackoverflow.com/questions/25288646/is-there-a-destructor-in-r-reference-class):
    ```R
    myclass$methods(
        finalize = function() {
            message("I am finalizing this thing...")
        }
    )
    ```
   In (2) you say there is such a mechanism implemented for temporary arrays and they get deleted when out of scope. I guess I am thinking of the same mechanism but for `db`.
2. Instead of storing the username/password in the temporary array, store the session ID or even the `db` instance.
3. Re: Corner case. In the `db` instance you can store a list of all the temporary arrays. When `scidbdisconnect` is called, you first remove all the temporary arrays and then release the session.

[This](https://github.com/Paradigm4/SciDB-Py/blob/master/scidbpy/db.py#L481) is the `finalize`    function used in SciDB-Py for pruning temporary arrays. Each `Array` stores a copy of the `db` object. This is how we are able to delete the array. This won't work if the session is released independently by the `db` instance...

**Comment by ksens** [comment]
Moved to https://github.com/Paradigm4/SciDBR/issues/183
