### ISSUE TITLE
Does shim still crash on empty credentials?

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/shim#79]
Check this on the latest 18.1. The use case is to have SciDB authentication turned on and then try to connect without supplying the "auth" object.

**Comment by rvernica** [comment]
I added a `auth.sh` test script to try out various credentials scenarios (no credentials, only username, wrong username, etc.). The script requires `security=password` and it is not included in the automated testing done by TravisCI.

Shim `session-auth` has been tested with SciDB `16.9` and no problems have been found.

Shim `v17.x-session-auth` has been tested with SciDB `18.1` and the problem has been fixed in bf564f6e8217adc03fb4321354eb1d9cb4c992d5

Here is the behavior for SciDB `16.9` and `18.1` for different credentials scenarios:

Scenario | Endpoint | Status code in `16.9` | Status code in `18.1`
--- | --- | --- | ---
No or incomplete credentials | /new_session    | 200 [1] | 401
(continued)                            | /execute_query | 406 | N/A
| | |
Wrong credentials                 | /new_session    | 401 | 401

[1] In SciDB `16.9` with `security=password`, client connections with no credentials are not detected as errors. A valid session is created. An error is triggered later when query is executed.
