### ISSUE TITLE
Can't retrieve 500-attribute array

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/shim#94]
@rvernica this looks interesting. We simulate an array with 500 attributes (they are all null). It looks like the binary save string (int64,string,string,....) gets "cut off" and the query fails. I don't know if its a problem in SciDBR or in shim:

```{r}
> system("echo a b c > /tmp/foo")
> iquery(db, "store(aio_input('/tmp/foo', 'num_attributes=500'), LOAD.TMP)")
> iquery(db, "scan(LOAD.TMP)", return=T
+ )
Error: HTTP error 406
SystemException in file: AioSaveSettings.h function: AioSaveSettings line: 298
Error id: scidb::SCIDB_SE_INTERNAL::SCIDB_LE_ILLEGAL_OPERATION
Error description: Internal SciDB error. Illegal operation: format must be either 'tdv', 'tsv', 'csv+', 'arrow', or a binary spec such as '(int64,double,string null)'.

```

**Comment by rvernica** [comment]
I confirmed that this is Shim issue. It is due to the fixed size of the `save` argument to the request. The `save` argument stores the format in which the data will be written to disk.

I made the `save` argument have dynamic size and added a test like `query=build(<a0:string,...a500:string>[i=1:1], '[(null,...null)]',true)&save=(string null,...string null)`

This seems to work fine with HTTP, but runs into issues with HTTP Digest Authentication. There might be another buffer overflow somewhere else. I will keep looking into this and also check with HTTPS.

**Comment by rvernica** [comment]
I committed the fix as described above.

If digest authentication is used, the URI is limited in `mongoose.c` to `8192` bytes (see [here](https://github.com/Paradigm4/shim/blob/88bd47ec25f4fd7632f823ccf043a7a3233deba5/src/mongoose.c#L261) and [here](https://github.com/Paradigm4/shim/blob/88bd47ec25f4fd7632f823ccf043a7a3233deba5/src/mongoose.c#L2501)). So, if the `query` or the `format` arguments are too long, the URI might exceed this limit. If this happens the authentication will fail, since the URI is truncated by the authentication function and the hashes won't match. The client will recived `401 Unauthorized`. We could extend this limit in `mongoose.c`.

**Comment by rvernica** [comment]
I checked again for memory leaks.
